name: goapp-ci-starter-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
            go-version: '>=1.17.0' 

      - name: Unit Testing
        run: go test   
